#!/usr/bin/env bash
# transfers a file from client to a server
file=$1
ip=$2
user=$3
path=$4

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -i "$path" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/
