#!/usr/bin/env bash
#Creating a script that uses a for loop
for i in "Best School"  "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School"
do
  echo "$i"
done 
