#!/usr/bin/env bash
while $n 
do
  echo -e "$n Best School \n" "Best School \n" "Best School \n" "Best School \n"  "Best School \n" "Best School \n" "Best School \n" "Best School \n" "Best School \n" "Best School"
  break
done

