#!/usr/bin/env bash
a=1
while [ $a -le 10 ]
do
        echo "Best School"
        if [ $a -eq 4 ]
        then
            echo "bad luck"
        
        elif [ $a -eq 8 ]
        then
            echo "bad luck"
        fi
        ((a++))
done