#!/usr/bin/env bash
#creating nests in bash
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -lt 60 ]
     do
            echo "$minutes"
            ((minutes++))
    done
    ((hour++))
done
