#!/usr/bin/env bash
# change ip for local host and facebook
cp /etc/hosts ~/hosts.new
sed -i "/127.0.0.1/127.0.0.2/" ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
