#!/usr/bin/env bash
# script that change the user in less lines
sudo pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart